# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x07user.v1\"\x1c\n\x0eGetUserRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"S\n\x11\x43reateUserRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\tfirstname\x18\x02 \x01(\t\x12\x10\n\x08lastname\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t\"b\n\x0cUserResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\tfirstname\x18\x02 \x01(\t\x12\x10\n\x08lastname\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t\x12\x12\n\ncreated_at\x18\x05 \x01(\t\"%\n\x12\x43reateUserResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x8f\x01\n\x0bUserService\x12\x39\n\x07GetUser\x12\x17.user.v1.GetUserRequest\x1a\x15.user.v1.UserResponse\x12\x45\n\nCreateUser\x12\x1a.user.v1.CreateUserRequest\x1a\x1b.user.v1.CreateUserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETUSERREQUEST']._serialized_start=23
  _globals['_GETUSERREQUEST']._serialized_end=51
  _globals['_CREATEUSERREQUEST']._serialized_start=53
  _globals['_CREATEUSERREQUEST']._serialized_end=136
  _globals['_USERRESPONSE']._serialized_start=138
  _globals['_USERRESPONSE']._serialized_end=236
  _globals['_CREATEUSERRESPONSE']._serialized_start=238
  _globals['_CREATEUSERRESPONSE']._serialized_end=275
  _globals['_USERSERVICE']._serialized_start=278
  _globals['_USERSERVICE']._serialized_end=421
# @@protoc_insertion_point(module_scope)
